import nanostat_script
from collections import OrderedDict

def test_get_data():
    """ This test verifies functionality by comparing current output to a previous one """
    report_path = "input/report_PAM08544_20220830_1308_bb13fa5d.html"
    data = nanostat_script.get_data(report_path)

    assert data == {'Estimated bases': '15.48 Gb',
                    'Data produced': '155.71 GB',
                    'Reads generated': '4.72 M',
                    'Estimated N50': '12.33 kb',
                    'Reads called': '100%',
                    'Q score': '9',
                    'Bases passed': '11.97 Gb',
                    'Bases failed': '2.7 Gb',
                    'Elapsed time': '72 hours of 72 hours',
                    'Run status': 'Finished',
                    'Flow Cell type': 'FLO-PRO002',
                    'Flow Cell ID': 'PAM08544',
                    'Kit type': 'SQK-LSK109',
                    'Specified run length': '72hrs',
                    'Active channel selection': 'On',
                    'Pore scan freq.': '1.5hrs',
                    'Bias voltage (initial)': '-163mV',
                    'Bias voltage (final)': '-2mV',
                    'Reserved pores': 'On',
                    'Basecalling': 'dna_r9.4.1_450bps_hac_prom',
                    'FAST5 output': 'vbz_compress',
                    'FAST5 reads per file': '4000',
                    'FASTQ output': 'compress',
                    'FASTQ reads per file': '4000',
                    'BAM output': 'Off',
                    'Bulk file output': 'Off',
                    'Data location': '/data/data-offload/P26321/P26321/20220830_1304_2E_PAM08544_bb13fa5d',
                    'MinKNOW': '22.05.7',
                    'Bream': '7.1.3',
                    'Configuration': '5.1.5',
                    'Guppy': '6.1.5',
                    'MinKNOW Core': '5.1.0',
                    'Run duration': '30 Aug 22, 13:04 — 02 Sep 22, 13:08',
                    'Experiment name': 'P26321',
                    'Sample name': 'P26321',
                    'Instrument position': '2E',
                    'Protocol run ID': 'bb13fa5d-6b73-4b0f-bed4-c94e9b4674b8',
                    'barcode_reads': OrderedDict([('barcode01', '232'),
                                ('barcode02', '188'),
                                ('barcode03', '210'),
                                ('barcode04', '212669'),
                                ('barcode05', '144'),
                                ('barcode06', '205'),
                                ('barcode07', '47'),
                                ('barcode08', '411'),
                                ('barcode09', '151'),
                                ('barcode10', '105'),
                                ('barcode11', '108'),
                                ('barcode12', '943'),
                                ('barcode13', '92'),
                                ('barcode14', '109'),
                                ('barcode15', '194'),
                                ('barcode16', '31785'),
                                ('barcode17', '112'),
                                ('barcode18', '160'),
                                ('barcode19', '301'),
                                ('barcode20', '390'),
                                ('barcode21', '243'),
                                ('barcode22', '192'),
                                ('barcode23', '283'),
                                ('barcode24', '491'),
                                ('barcode25', '516'),
                                ('barcode26', '422'),
                                ('barcode27', '129'),
                                ('barcode28', '86842'),
                                ('barcode29', '217'),
                                ('barcode30', '186'),
                                ('barcode31', '388'),
                                ('barcode32', '591'),
                                ('barcode33', '252'),
                                ('barcode34', '226'),
                                ('barcode35', '437'),
                                ('barcode36', '63'),
                                ('barcode37', '442'),
                                ('barcode38', '202'),
                                ('barcode39', '291'),
                                ('barcode40', '291137'),
                                ('barcode41', '239'),
                                ('barcode42', '511'),
                                ('barcode43', '867'),
                                ('barcode44', '60'),
                                ('barcode45', '245'),
                                ('barcode46', '618'),
                                ('barcode47', '121'),
                                ('barcode48', '428'),
                                ('barcode49', '227'),
                                ('barcode50', '134'),
                                ('barcode51', '814'),
                                ('barcode52', '148'),
                                ('barcode53', '205'),
                                ('barcode54', '333'),
                                ('barcode55', '202'),
                                ('barcode56', '344'),
                                ('barcode57', '197'),
                                ('barcode58', '323'),
                                ('barcode59', '197'),
                                ('barcode60', '331'),
                                ('barcode61', '158'),
                                ('barcode62', '228'),
                                ('barcode63', '110'),
                                ('barcode64', '702'),
                                ('barcode65', '187'),
                                ('barcode66', '274'),
                                ('barcode67', '1220'),
                                ('barcode68', '187'),
                                ('barcode69', '260'),
                                ('barcode70', '144'),
                                ('barcode71', '280'),
                                ('barcode72', '371'),
                                ('barcode73', '84'),
                                ('barcode74', '181'),
                                ('barcode75', '231'),
                                ('barcode76', '11601'),
                                ('barcode77', '190'),
                                ('barcode78', '300'),
                                ('barcode79', '281'),
                                ('barcode80', '368'),
                                ('barcode81', '204'),
                                ('barcode82', '432'),
                                ('barcode83', '507'),
                                ('barcode84', '308'),
                                ('barcode85', '61'),
                                ('barcode86', '122'),
                                ('barcode87', '104'),
                                ('barcode88', '296'),
                                ('barcode89', '259'),
                                ('barcode90', '211'),
                                ('barcode91', '256'),
                                ('barcode92', '93'),
                                ('barcode93', '112'),
                                ('barcode94', '973'),
                                ('barcode95', '186'),
                                ('barcode96', '287')])}
